### ISSUE TITLE
En tant qu'utilisateur, j'aimerais pouvoir envoyer des occurrences de symptomes à mon médecin par mail

### ISSUE THREAD

**Issue by seza443** [GeoHealth/HAppi_backend#36]
J'aimerais pouvoir choisir une date à partir de laquelle envoyer des symptomes.
Un lien est envoyé par mail ( #35 ) au médecin (contenant certaines info sur l'utilisateur tels que son mail, son nom).
Le lien dirige vers une page https://github.com/GeoHealth/HAppi_frontend sur laquelle les données sont anonymisées. Le médecin doit pouvoir visualiser le même graphe sur l'app mobile + d'autres graphes (punch card, Google map avec geolocalisation des occurrences, ...)

**Comment by seza443** [comment]
Dans Sidekiq:
- [ ] Générer un token unique avec une date d'expiration
- [ ] Lier les occurrences choisies par l'utilisateur à ce token.
- [ ] Envoyer un mail au médecin avec le token dans l'URL

**Comment by seza443** [comment]
Generate URL
http://guides.rubyonrails.org/action_mailer_basics.html#generating-urls-in-action-mailer-views
